import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Recursive } from 'next/font/google'

const recursive = Recursive({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Drone Dash",
  description: "Generated by create next app",
  icons:{
    icon:'/icon.png',
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={recursive.className}
      >
        <Navbar/>
        <main className='flex bg-slate-50 grainy-light flex-col min-h-[calc(100vh-3.5rem-1px)]'>
          <div className='flex-1 flex flex-col h-full'>
            {children}
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
